Losses compensator improvements
powsybl/powsybl-entsoe pull request #147
Opened 2024-05-27 10:08 UTC by caioluke

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

- We don't compensate losses for branches that are connected to only one side
- Bug in edge case where both P1 and P2 are positive (one is really close to zero) and the sending terminal is incorrectly identified
- Set loads created to compensate losses to fictitious (will make a difference when https://github.com/powsybl/powsybl-open-loadflow/pull/1028 is merged)
- (Minor) Some java code could be enhanced

**What is the new behavior (if this is a feature change)?**
- Compensate losses for branches connected to only one side
- Sending terminal is always correctly identified
- Slack won't be distributed on fictitious loads created by losses compensator

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-05-27 15:39 UTC, OpenSuze commented on flow-decomposition/src/test/java/com/powsybl/flow_decomposition/LossesCompensationTests.java
> +    void testLossCompensationWithLineConnectedToOnlyOneSide() {
Thank you for this great test !
Could you add a test using only the LossCompensator and not the full flow decomposition please ? 
For example:
```suggestion
    /*
        Test flow decomposition with losses compensation in a simple network
          FR : bus1
          BE : bus2, bus3
                                   ____ bus3
                                  |      |
                                 l32     d3 (1)
                                  |
                bus1 --- l21 --- bus2
                 |                |
                g1 (3)           d2 (2)
         Line l32 is open at side 1 (bus 3)
         Line characteristics: (r,x,g,b) = (0.01, 0.1, 0.0, 0.5)
     */
   @Test
    void toBeRefactoredTest {
        String networkFileName = "lossesCompensatorLineConnectedToOneSide.xiidm";
        Network network = importNetwork(networkFileName);
        assertEquals(2, network.getLoadStream().count());
        LoadFlow.run(network, new LoadFlowParameters().setDc(AC_LOAD_FLOW));
        LossesCompensator lossesCompensator = new LossesCompensator(FlowDecompositionParameters.DEFAULT_LOSSES_COMPENSATION_EPSILON);
        lossesCompensator.run(network);
        assertEquals(5, network.getLoadStream().count());
        Load lossesb1 = network.getLoad("LOSSES b1");
        assertNotNull(lossesb1);
        assertEquals("b1_vl", lossesb1.getTerminal().getVoltageLevel().getId());
        assertEquals(0.061171, lossesb1.getP0(), 1e-6);
        Load lossesb2 = network.getLoad("LOSSES b2");
        assertNotNull(lossesb2);
        assertEquals("b2_vl", lossesb2.getTerminal().getVoltageLevel().getId());
        assertEquals(0.003581, lossesb2.getP0(), 1e-6);
        Load lossesb3 = network.getLoad("LOSSES b3");
        assertNotNull(lossesb3);
        assertEquals("b3_vl", lossesb3.getTerminal().getVoltageLevel().getId());
        assertEquals(0.0, lossesb3.getP0(), 1e-6);
    }
```

2024-05-30 16:10 UTC, OpenSuze commented on flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionObserverTest.java
> +        String lossesId = LossesCompensator.getLossesId("");
Could you extract a constant "LOSSES" in LossesCompensator instead of using this method please ?

2024-05-30 16:10 UTC, OpenSuze commented on flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionObserverList.java
> +        Map<String, Double> results = new ReferenceNodalInjectionComputer().run(nodeListWithoutCompensatedLosses);
Remove this filtering, see #149

2024-06-03 13:00 UTC, OpenSuze approved these changes

2024-06-04 09:13 UTC, OpenSuze commented
I have force pushed to fix the DCO.

2024-06-04 09:18 UTC, OpenSuze approved these changes

2024-06-05 07:21 UTC, phiedw requested changes

2024-06-06 09:38 UTC, phiedw approved these changes

2024-06-06 12:04 UTC, merged