Add parameter to output flow decomposition results for paired dangling lines
powsybl/powsybl-entsoe pull request #162
Opened 2024-09-24 09:27 UTC by caioluke

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

As of today, it is not possible to have flow decomposition results for each half line (paired dangling line) of a tie line.

**What is the new behavior (if this is a feature change)?**
A new flow decomposition parameter (boolean - `enableResultsForPairedHalfLines`) will allow to produce flow decomposition results for these paired half lines.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-09-24 09:28 UTC, caioluke commented
@OpenSuze if you validate the idea (adding a flow decomposition parameter), I will add some docs!

2024-10-04 10:13 UTC, obrix requested changes

2024-10-08 11:52 UTC, OpenSuze requested changes
Thank you for this PR !
Sorry for the delay

2024-10-08 11:52 UTC, OpenSuze commented on flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionParameters.java
Could you use the `XnecProvider` interface instead of adding a new parameter please ?

For example, when using `XnecProviderByIds` with a dangling line Id, the results should contain a `DecomposedFlow` for this Id.

This will require to ensure that the dangling line is paired (to find the corresponding tie line) because flow decomposition on an unpaired dangling line does not make sense for me (no loop flow).

Maybe, you could provide a new `XnecProvider` implementation called `XnecProviderAllPairedDanglingLines`

2024-10-28 09:01 UTC, caioluke commented
After [some discussion in this similar PR](https://github.com/powsybl/powsybl-entsoe/pull/173#issuecomment-2422331605), I understand that having different flow decompositions for paired dangling lines makes no sense.
Thanks for the help!

2024-10-28 09:01 UTC, closed without merging